apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
    spec:
      containers:
        -
          name: {{ .Chart.Name }}
          image: {{ template "super-app.dockerRegistry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            -
              name: MY_DOMAIN
              value: {{ .Values.domain }}
